import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

import { api } from "~/utils/api";

import Navbar from "~/components/navigation/top-navigation";
import CreateForm from "~/components/ad/create-ad";

import { Plus } from "lucide-react";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "~/components/ui/dialog";

const Home: NextPage = () => {
  const { data: ads, isFetching } = api.ad.list.useQuery(undefined, {
    refetchOnWindowFocus: false,
  });

  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (isFetching && open) {
      setOpen(false);
    }
  }, [isFetching, open]);

  return (
    <>
      <Head>
        <title>Treddy Marketplace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-196x196.png" />
      </Head>

      <Navbar />

      <main className="flex min-h-screen flex-col">
        <div className="container flex flex-col items-center justify-center gap-12 py-16 sm:px-4 ">
          <h1 className="mb-12 text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <Link href="/">
              Treddy <span className="text-[#79bb97]">Marketplace</span>
            </Link>
          </h1>

          <Dialog open={open} onOpenChange={(open) => setOpen(open)}>
            <DialogTrigger
              className="flex items-center gap-2 rounded border bg-white p-4 text-[#155d64] hover:bg-gray-100"
              onClick={() => setOpen(true)}
            >
              <Plus />
              Skapa annons
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Skapa annons</DialogTitle>
                <DialogDescription>Skapa din annons</DialogDescription>
                <CreateForm />
              </DialogHeader>
            </DialogContent>
          </Dialog>

          <div className="grid grid-cols-1 justify-center gap-4 sm:grid-cols-3 md:grid-cols-5 md:gap-8">
            {ads &&
              ads.map((ad, i) => (
                <div key={i} className="flex flex-col rounded bg-white p-2">
                  <div className="relative bg-white">
                    <Link href={`/ads/${ad.id}`}>
                      <Image
                        src="/no-img.svg"
                        alt=""
                        className="rounded-tl rounded-tr"
                        width={250}
                        height={250}
                      />
                    </Link>
                  </div>

                  <div className="flex flex-col gap-2 bg-white p-2">
                    <h3 className="text-[1.25rem] font-bold">{ad.name}</h3>

                    <div className="text-md flex justify-between">
                      <div className="text-sm">{ad.price}:-</div>
                      <div className="text-sm">Stockholm</div>
                    </div>

                    {ad.seller && (
                      <div className="flex items-center justify-end gap-2 text-xs">
                        {ad.seller.name}
                      </div>
                    )}

                    {ad?.treddy?.dealId && (
                      <div className="flex items-center justify-end gap-2 text-xs">
                        <Image src="/tr.svg" alt="" width={16} height={16} />
                        Frakt och trygg betalning
                      </div>
                    )}
                  </div>
                </div>
              ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
